[package]
name = "nvavif_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "_nvavif_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }
ffmpeg-next = "8.1.0"
avif-serialize = "0.8.8"
rayon = "1.11.0"
bytemuck = { version = "1", features = ["derive"] }
rav1e = { version = "0.7.1", default-features = false, features = ["threading"] }